apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  # Flask
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "3030"
  FLASK_DEBUG: "True"
  # Auth service
  AUTH_SVC_ADDRESS: "http://auth:3000"
  # MongoDB
  MONGODB_VIDEO_URI: "mongodb://host.minikube.internal:27017/videos"
  MONGODB_MP3_URI: "mongodb://host.minikube.internal:27017/mp3s"
  GRIDFS_VIDEO_NAME: "video"
  GRIDFS_MP3_NAME: "mp3"
  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_VIDEO_QUEUE: "video"
  RABBITMQ_MP3_QUEUE: "mp3"
