apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  # MongoDB
  MONGODB_HOST: "host.minikube.internal"
  MONGODB_PORT: "27017"
  MONGODB_VIDEO_DB: "videos"
  MONGODB_MP3_DB: "mp3s"
  GRIDFS_VIDEO_NAME: "video"
  GRIDFS_MP3_NAME: "mp3"
  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_VIDEO_QUEUE: "video"
  RABBITMQ_MP3_QUEUE: "mp3"
